### ISSUE TITLE
SNR decompiler not working

### ISSUE THREAD

**Issue by OneSeri** [DCNick3/ShinDataUtil#11]
```
D:\Games\vns\normal\sss>dotnet run scenario-decompile D:\Games\vns\normal\sss\ee\ss\main.snr D:\Games\vns\normal\ShinDataUtil-master\ee\ss\main
D:\Games\vns\normal\sss\ShinDataUtil.csproj : warning NU1902: Package 'SixLabors.ImageSharp' 1.0.0-beta0007 has a known
 moderate severity vulnerability, https://github.com/advisories/GHSA-5x7m-6737-26cr
D:\Games\vns\normal\sss\ShinDataUtil.csproj : warning NU1903: Package 'SixLabors.ImageSharp' 1.0.0-beta0007 has a known
 high severity vulnerability, https://github.com/advisories/GHSA-63p8-c4ww-9cg7
D:\Games\vns\normal\sss\ShinDataUtil.csproj : warning NU1903: Package 'SixLabors.ImageSharp' 1.0.0-beta0007 has a known
 high severity vulnerability, https://github.com/advisories/GHSA-65x7-c272-7g7r
D:\Games\vns\normal\sss\ShinDataUtil.csproj : warning NU1902: Package 'SixLabors.ImageSharp' 1.0.0-beta0007 has a known
 moderate severity vulnerability, https://github.com/advisories/GHSA-g85r-6x2q-45w7
D:\Games\vns\normal\sss\ShinDataUtil.csproj : warning NU1902: Package 'SixLabors.ImageSharp' 1.0.0-beta0007 has a known
 moderate severity vulnerability, https://github.com/advisories/GHSA-qxrv-gp6x-rc23
D:\Games\vns\normal\sss\ShinDataUtil.csproj : warning NU1902: Package 'SixLabors.ImageSharp' 1.0.0-beta0007 has a known
 moderate severity vulnerability, https://github.com/advisories/GHSA-5x7m-6737-26cr
D:\Games\vns\normal\sss\ShinDataUtil.csproj : warning NU1903: Package 'SixLabors.ImageSharp' 1.0.0-beta0007 has a known
 high severity vulnerability, https://github.com/advisories/GHSA-63p8-c4ww-9cg7
D:\Games\vns\normal\sss\ShinDataUtil.csproj : warning NU1903: Package 'SixLabors.ImageSharp' 1.0.0-beta0007 has a known
 high severity vulnerability, https://github.com/advisories/GHSA-65x7-c272-7g7r
D:\Games\vns\normal\sss\ShinDataUtil.csproj : warning NU1902: Package 'SixLabors.ImageSharp' 1.0.0-beta0007 has a known
 moderate severity vulnerability, https://github.com/advisories/GHSA-g85r-6x2q-45w7
D:\Games\vns\normal\sss\ShinDataUtil.csproj : warning NU1902: Package 'SixLabors.ImageSharp' 1.0.0-beta0007 has a known
 moderate severity vulnerability, https://github.com/advisories/GHSA-qxrv-gp6x-rc23
D:\Games\vns\normal\sss\Compression\ShinTxaEncoder.cs(92,28): warning CS8601: Возможно, назначение-ссылка, допускающее
значение NULL. [D:\Games\vns\normal\sss\ShinDataUtil.csproj]
D:\Games\vns\normal\sss\Util\MessageTextLayouter.cs(180,21): warning CS0675: Побитовый оператор "ИЛИ" применен к операн
ду, расширенному знаком; рекомендуется предварительное приведение к меньшему беззнаковому типу [D:\Games\vns\normal\sss
\ShinDataUtil.csproj]
D:\Games\vns\normal\sss\Util\MessageTextLayouter.cs(180,21): warning CS0675: Побитовый оператор "ИЛИ" применен к операн
ду, расширенному знаком; рекомендуется предварительное приведение к меньшему беззнаковому типу [D:\Games\vns\normal\sss
\ShinDataUtil.csproj]
D:\Games\vns\normal\sss\Util\MessageTextLayouter.cs(353,17): warning CS0162: Обнаружен недостижимый код [D:\Games\vns\n
ormal\sss\ShinDataUtil.csproj]
D:\Games\vns\normal\sss\Compression\Scenario\Parser.cs(651,88): warning SYSLIB0051: "Exception.Exception(SerializationI
nfo, StreamingContext)" является устаревшим: 'This API supports obsolete formatter-based serialization. It should not b
e called or extended by application code.' (https://aka.ms/dotnet-warnings/SYSLIB0051) [D:\Games\vns\normal\sss\ShinDat
aUtil.csproj]
D:\Games\vns\normal\sss\Compression\Scenario\Parser.cs(632,96): warning SYSLIB0051: "Exception.Exception(SerializationI
nfo, StreamingContext)" является устаревшим: 'This API supports obsolete formatter-based serialization. It should not b
e called or extended by application code.' (https://aka.ms/dotnet-warnings/SYSLIB0051) [D:\Games\vns\normal\sss\ShinDat
aUtil.csproj]
D:\Games\vns\normal\sss\Util\MessageTextLayouter.cs(120,27): warning CS0649: Полю "MessageTextLayouter.LineInfo.f_4" ни
где не присваивается значение, поэтому оно всегда будет иметь значение по умолчанию 0. [D:\Games\vns\normal\sss\ShinDat
aUtil.csproj]
D:\Games\vns\normal\sss\Util\MessageTextLayouter.cs(123,27): warning CS0649: Полю "MessageTextLayouter.LineInfo.f_10" н
игде не присваивается значение, поэтому оно всегда будет иметь значение по умолчанию 0. [D:\Games\vns\normal\sss\ShinDa
taUtil.csproj]
D:\Games\vns\normal\sss\Util\MessageTextLayouter.cs(122,27): warning CS0649: Полю "MessageTextLayouter.LineInfo.f_c" ни
где не присваивается значение, поэтому оно всегда будет иметь значение по умолчанию 0. [D:\Games\vns\normal\sss\ShinDat
aUtil.csproj]
D:\Games\vns\normal\sss\Util\MessageTextLayouter.cs(121,27): warning CS0649: Полю "MessageTextLayouter.LineInfo.f_8" ни
где не присваивается значение, поэтому оно всегда будет иметь значение по умолчанию 0. [D:\Games\vns\normal\sss\ShinDat
aUtil.csproj]
D:\Games\vns\normal\sss\Util\MessageTextLayouter.cs(119,27): warning CS0649: Полю "MessageTextLayouter.LineInfo.f_0" ни
где не присваивается значение, поэтому оно всегда будет иметь значение по умолчанию 0. [D:\Games\vns\normal\sss\ShinDat
aUtil.csproj]
D:\Games\vns\normal\sss\Util\MessageTextLayouter.cs(21,24): warning CS0414: Полю "MessageTextLayouter._defaultFontSize"
 присвоено значение, но оно ни разу не использовано. [D:\Games\vns\normal\sss\ShinDataUtil.csproj]
D:\Games\vns\normal\sss\Util\MessageTextLayouter.cs(82,21): warning CS0414: Полю "MessageTextLayouter._i114" присвоено
значение, но оно ни разу не использовано. [D:\Games\vns\normal\sss\ShinDataUtil.csproj]
D:\Games\vns\normal\sss\Util\MessageTextLayouter.cs(73,21): warning CS0414: Полю "MessageTextLayouter._sectionIndex" пр
исвоено значение, но оно ни разу не использовано. [D:\Games\vns\normal\sss\ShinDataUtil.csproj]
D:\Games\vns\normal\sss\Util\MessageTextLayouter.cs(71,22): warning CS0414: Полю "MessageTextLayouter._someVoiceModifie
r" присвоено значение, но оно ни разу не использовано. [D:\Games\vns\normal\sss\ShinDataUtil.csproj]
D:\Games\vns\normal\sss\Util\MessageTextLayouter.cs(67,24): warning CS0414: Полю "MessageTextLayouter._voiceVolume" при
своено значение, но оно ни разу не использовано. [D:\Games\vns\normal\sss\ShinDataUtil.csproj]
D:\Games\vns\normal\sss\Util\MessageTextLayouter.cs(84,21): warning CS0414: Полю "MessageTextLayouter._i11c" присвоено
значение, но оно ни разу не использовано. [D:\Games\vns\normal\sss\ShinDataUtil.csproj]
D:\Games\vns\normal\sss\Util\MessageTextLayouter.cs(74,21): warning CS0414: Полю "MessageTextLayouter._commandCount" пр
исвоено значение, но оно ни разу не использовано. [D:\Games\vns\normal\sss\ShinDataUtil.csproj]
D:\Games\vns\normal\sss\Util\MessageTextLayouter.cs(70,22): warning CS0414: Полю "MessageTextLayouter._someCount" присв
оено значение, но оно ни разу не использовано. [D:\Games\vns\normal\sss\ShinDataUtil.csproj]
D:\Games\vns\normal\sss\Util\MessageTextLayouter.cs(83,21): warning CS0414: Полю "MessageTextLayouter._i118" присвоено
значение, но оно ни разу не использовано. [D:\Games\vns\normal\sss\ShinDataUtil.csproj]
Unhandled exception. System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at ShinDataUtil.Decompression.Scenario.ShinScenarioDecompiler.ReadString(ReadOnlySpan`1& data) in D:\Games\vns\normal\sss\Decompression\Scenario\ShinScenarioDecompiler.cs:line 20
   at ShinDataUtil.Decompression.Scenario.ShinScenarioDecompiler.HandleStringsSection(ReadOnlySpan`1 data) in D:\Games\vns\normal\sss\Decompression\Scenario\ShinScenarioDecompiler.cs:line 48
   at ShinDataUtil.Decompression.Scenario.ShinScenarioDecompiler.ReadHead(ReadOnlySpan`1 data, ScenarioHeader header) in D:\Games\vns\normal\sss\Decompression\Scenario\ShinScenarioDecompiler.cs:line 257
   at ShinDataUtil.Decompression.Scenario.ShinScenarioDecompiler.Decompile(ReadOnlyMemory`1 memory, String destinationDirectory) in D:\Games\vns\normal\sss\Decompression\Scenario\ShinScenarioDecompiler.cs:line 321
   at ShinDataUtil.Program.ScenarioDecompile(ReadOnlyMemory`1 snrdata, String _, String outname, ImmutableArray`1 options) in D:\Games\vns\normal\sss\Program.cs:line 560
   at ShinDataUtil.Program.ActionList.<>c__DisplayClass7_0.<AddSingleFileProcessingAction>b__0(ReadOnlySpan`1 args) in D:\Games\vns\normal\sss\Program.cs:line 777
   at ShinDataUtil.Program.ActionList.Execute(String actionname, ReadOnlySpan`1 args) in D:\Games\vns\normal\sss\Program.cs:line 813
   at ShinDataUtil.Program.MainWrap(String[] args) in D:\Games\vns\normal\sss\Program.cs:line 850
   at ShinDataUtil.Program.Main(String[] args) in D:\Games\vns\normal\sss\Program.cs:line 857
```

**Comment by masagrator** [comment]
What game you are trying to decompile?

**Comment by OneSeri** [comment]
> What game you are trying to decompile?

umineko saku

**Comment by masagrator** [comment]
Well, did you read Overview?

 https://github.com/DCNick3/ShinDataUtil#overview

**Comment by OneSeri** [comment]
Read it, but not carefully....

**Comment by DCNick3** [comment]
You can use `sdu` from https://github.com/DCNick3/shin if what you want is scenario decompilation.

I am also working on a tool that would work better for translations: https://github.com/DCNick3/shin-translation-tools. Let me know if you need umineko support there, it's pretty easy for me to add.
