### ISSUE TITLE
After last commit can't pack anything to new ROM

### ISSUE THREAD

**Issue by masagrator** [DCNick3/ShinDataUtil#4]
Even if it's just one file in root. Windows and Ubuntu are showing the same error.
Command:
```
dotnet shindatautil.dll rom-build ./patch.rom ./quiz.txa quiz.txa
```

Result
```
Process terminated. Assertion Failed
   at ShinDataUtil.Compression.ShinRomOperations.<BuildRom>g__AddEntry|1_0(IFileProvider source, String targetName, <>c__DisplayClass1_0& ) in C:\Users\Admin\Documents\Switch\Higurashi\ShinDataUtil2\ShinDataUtil\Compression\ShinRomOperations.cs:line 73
   at ShinDataUtil.Compression.ShinRomOperations.BuildRom(Stream outrom, IEnumerable`1 files) in C:\Users\Admin\Documents\Switch\Higurashi\ShinDataUtil2\ShinDataUtil\Compression\ShinRomOperations.cs:line 122
   at ShinDataUtil.Compression.ShinRomOperations.BuildRom(Stream outrom, IEnumerable`1 files) in C:\Users\Admin\Documents\Switch\Higurashi\ShinDataUtil2\ShinDataUtil\Compression\ShinRomOperations.cs:line 230
   at ShinDataUtil.Program.RomBuild(ReadOnlySpan`1 args) in C:\Users\Admin\Documents\Switch\Higurashi\ShinDataUtil2\ShinDataUtil\Program.cs:line 439
   at ShinDataUtil.Program.ActionList.Execute(String actionname, ReadOnlySpan`1 args) in C:\Users\Admin\Documents\Switch\Higurashi\ShinDataUtil2\ShinDataUtil\Program.cs:line 511
   at ShinDataUtil.Program.MainWrap(String[] args) in C:\Users\Admin\Documents\Switch\Higurashi\ShinDataUtil2\ShinDataUtil\Program.cs:line 542
   at ShinDataUtil.Program.Main(String[] args) in C:\Users\Admin\Documents\Switch\Higurashi\ShinDataUtil2\ShinDataUtil\Program.cs:line 549
```

Build with Visual Studio 2019 on Windows, dotnet 5.0.

Beside it's possible to write new function for packing that will just recursively scan folder we provide as argument and pack all of files inside? This way we can avoid Windows cmd limit that is 2048 characters per command (and will make life easier when putting new files regularly)

**Comment by masagrator** [comment]
Nvm. My fault. It's lacking `/` on target name

**Comment by DCNick3** [comment]
Will probably change the error message to something more meaningful

**Comment by DCNick3** [comment]
Done in a664457688d22dc2fe1bc5374353afc335050a34
