### ISSUE TITLE
Can't decompress anything 

### ISSUE THREAD

**Issue by goutosama** [DCNick3/ShinDataUtil#5]
Maybe I forgot to install something or not doing it right? 

Here's log also:
```
PS G:\Translations\ShinDataUtil-master\bin\Debug\netcoreapp5.0> dotnet ShinDataUtil.dll txa-extract .\input\config.txa .\output
Process terminated. Assertion Failed
   at ShinDataUtil.Decompression.ShinTxaExtractor.Extract(ReadOnlySpan`1 data, String destinationDirectory, Boolean ignoreFileSize) in G:\Translations\ShinDataUtil-master\Decompression\ShinTxaExtractor.cs:line 24
   at ShinDataUtil.Program.TxaExtract(ReadOnlyMemory`1 txadata, String _, String outname, ImmutableArray`1 options) in G:\Translations\ShinDataUtil-master\Program.cs:line 518
   at ShinDataUtil.Program.ActionList.<>c__DisplayClass7_0.<AddSingleFileProcessingAction>b__0(ReadOnlySpan`1 args) in G:\Translations\ShinDataUtil-master\Program.cs:line 777
   at ShinDataUtil.Program.ActionList.Execute(String actionname, ReadOnlySpan`1 args) in G:\Translations\ShinDataUtil-master\Program.cs:line 813
   at ShinDataUtil.Program.MainWrap(String[] args) in G:\Translations\ShinDataUtil-master\Program.cs:line 850
   at ShinDataUtil.Program.Main(String[] args) in G:\Translations\ShinDataUtil-master\Program.cs:line 857
```

**Comment by DCNick3** [comment]
No, you are fine. This error says that some assumption about the files I had while writing this was violated.
What are you trying to decompress? This was well-tested only on Higurashi no Naku Koro ni and Kono Subarashii Sekai ni Shukufuku wo! Kibou no Meikyuu to Tsudoishi Boukenshata Plus (in separate branch)

**Comment by goutosama** [comment]
I'm trying to decompress files from Higurashi no Naku Koro ni Sui on PS Vita

**Comment by DCNick3** [comment]
Ah, makes sense, never tried that, was working with the switch one. Yours should be the earlier one.

Maybe I will look at it & add _some_ support if it wouldn't be too much of a pain...
What are you planning to do (that is, which formats do you need? :P)

**Comment by goutosama** [comment]
Well, I thought about porting English translation to PS Vita, so I think I need .txa files with buttons, menus, etc. and files with actual game text (if fnt file already have English in it)

**Comment by DCNick3** [comment]
Hmm, nice. Did you look at the amazing [work](https://github.com/masagrator/HigurashiENX) @masagrator did for the switch port? (That's a scary amount of effort TBH though).

Expect most of the work to come from the scenario. txa can probably be implemented relatively easily, not so sure for the scenario, might be a lot of work...

BTW, do you mind using some IM like Telegram ([t.me/DCNick3](https://t.me/DCNick3)) or Discord (`DCNick3#0980`)?

**Comment by goutosama** [comment]
I found your tool only because of @masagrator work)
And yeah, I can use either of messagers, maybe Telegram is better
